### ISSUE TITLE
Add Achievements (SUGGESTION)

### ISSUE THREAD

**Issue by HDVinnie** [gstt/laravel-achievements#11]
Is there a way down the road to make logic/frontend so one can create/edit achievements on the fly which could be integrated into a existing admin panel or something. That way staff of site could add new Achievements from site and not have to use terminal and edit code in like sublime text?

I know this is long shot and probably not easy todo with how the Achievements system works now but thought i would throw the idea out there as it would make it more user friendly.

**Comment by gabriel-simonetti** [comment]
There's not actually a problem with adding achievements by the staff via an admin panel, but you'd need to have a developer change the source code anyway in order to create the unlock condition. Without changing the source, you'd only have an achievement which nobody can actually progress on, or unlock.

**Comment by HDVinnie** [comment]
makes sense. Didn't think about the unlock condition part! I hope you don't mind all the questions and suggestions some valid and some not. Just like this package and have been trying to get better and better at laravel for awhile now

**Comment by gabriel-simonetti** [comment]
Keep making them! Questions and suggestions will only make the package better. :D

**Comment by forgottencreature** [comment]
Aside from the fact that you would have to implement it in the code, I'm curious how you would go about creating achievements from an admin panel? Would you just execute the artisan command from your controller to generate the new files?

**Comment by gabriel-simonetti** [comment]
Yes, I would create Achievements from an admin panel by running the artisan command from the controller.

In case you need to edit them (for example, changing the name, description or points required to unlock the Achievement) all you need to do is alter the values in the achievement_details table, since they take precedence over the values declared on the Achievement class.
