### ISSUE TITLE
Unlock/Progress Events

### ISSUE THREAD

**Issue by HDVinnie** [gstt/laravel-achievements#15]
Hello. How am I able to use sweetalert2 for these events?I would like a popup like this when progress or a unlock is made.

https://codepen.io/anon/pen/yXXGPy

Is this possible and if not what to you recommend for alerts? I use toastr for my sites alerts but wanted something little pronounced for achievement alerts.

Thanks.

**Comment by gabriel-simonetti** [comment]
Yes, you could do that using swal. A simple (but not the best) way to achieve this is by implementing a listener on the `Gstt\Achievements\Event\Unlocked` Event and implement a session variable containing the unlocked Achievement. Here's a quick tutorial:

**Step 1: Implement a Listener**
You need a listener in order to receive an alert whenever an Achievement is unlocked. Create a file called "AchievementUnlocked" under the folder "app\Listeners":

```php
<?php

namespace App\Listeners;

use Session;
use Gstt\Model\AchievementProgress;
use Gstt\Achievements\Event\Unlocked;

class AchievementUnlocked
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  OrderShipped  $event
     * @return void
     */
    public function handle(Unlocked $event)
    {
        // There's an AchievementProgress instance located on $event->progress
        Session::flash('achievement', $event->progress->details->name);
    }
}
```

This listener triggers the handle() method whenever an Achievement is unlocked, and this method will add the Achievement name to a Session variable called 'achievement'.

**Step 2: Register the Listener**
On your `EventServiceProvider`, you must register the Listener you just created to the Event. You can do that appending this to the `$listen` mapper:

```php
protected $listen = [
    'Gstt\Achievements\Event\Unlocked' => [
        'App\Listeners\AchievementUnlocked',
    ],
];
```
This will tell your Laravel app that, whenever the `Gstt\Achievements\Event\Unlocked` is triggered, the `App\Listeners\AchievementUnlocked` listener must be called.

**Step 3: Displaying the Achievement on HTML**
Now you just to display this on the HTML. Add this to the `layout.blade.php` file you're using for logged in users:

```html
@if(Session::has('achievement'))
<script type="text/javascript">
    swal({
        title: 'Awesome !',
        text: 'You Unlocked "{{Session::get('achievement')}}" Achievment',
        type: 'success'
    });
</script>
@endif
```

Please let me know if this was helpful!

**Comment by HDVinnie** [comment]
champion! thanks so much for you package and awesome support!

**Comment by Cedcomps** [comment]
Support Diamond Edition lol

**Comment by gabriel-simonetti** [comment]
The best solution would be somewhat similar but would:

1) Allow for multiple achievement unlocks;
2) Populate a variable and let JavaScript code take care of making swal calls (instead of writing the direct call on JavaScript)

A different but similarly good solution (and, in my opinion, a more elegant solution as well) would be to create a restful API for querying achievements, and call it regularly.

**Comment by brjohnson4** [comment]
Oh, that's interesting. I had a similar situation where I at any time I could have 0, 1, or 2 achievements unlocked. I ended up implementing something similar to what you suggested. I defined the achievement types in my db (so a user can unlock a streak badge and a quantity badge at the same time) and put them in different session variables.
```
    public function handle(Unlocked $event)
    {
        if($event->progress->details->is_badge_streak == 1) {
            Session::flash('achievement-quantity', $event->progress->details);
        }
        if($event->progress->details-> is_badge_streak == 0) {
            Session::flash('achievement-streak', $event->progress->details);
        }
    }
```
Then in my controller:
```
		$badges = [];
		if(Session::has('achievement-quantity')) {
			array_push($badges, Session::get('achievement-quantity'));
			$this->createNotification(Session::get('achievement-quantity'));
		}

		if(Session::has('achievement-streak')) {
			array_push($badges, Session::get('achievement-streak'));
			$this->createNotification(Session::get('achievement-streak'));
		}
```
And put the $badges variable in my json response. Then I check for the length of the badges, and fire a modal if badges.length > 0 (I'm not using swal).

When you suggest the RESTful api to query achievements, I could essentially check the db to see if there are any new achievements that have yet to be displayed via modal, rather than relying on session variables. That seems a bit more simple than using an Event Listener.
