### ISSUE TITLE
Reset Specific Achievement

### ISSUE THREAD

**Issue by brjohnson4** [gstt/laravel-achievements#28]
I'm wondering if there is a way to edit an item in the achievement_progress table specifically? The problem that I have is that I need to reset the number of points back down to 0 if a user gets something wrong in whatever unlocked achievement they currently are working on.

If I just go into the DB table itself and edit the specific row with the code below, I'm able to reset the points, but it also loads every single achievement into the achievement_progress table for the user, and I don't want to clutter this table up with achievements that aren't valid for some time.

```
        $progress = $this->inProgressAchievements()->first();
        if($progress) {
            $progress->points = 0;
            $progress->save()
        }
```
This sends all possible achievements to the achievement_progress table, even though it does reset the achievement in progress.

**Comment by gabriel-simonetti** [comment]
Hi @brjohnson4!

You want just to reset the number of points without cluttering the table with invalid achievements. Is that correct? This was the behavior during beta testing, but on the release, it was changed to always maintain all achievements on the database.

In order to restore the behavior, you need to create a `config/achievements.php` file with this content:

```
<?php

return [
'locked_sync' => false
];
```

Thanks for bringing this to attention. This change was not documented on the code (just on the changelog for the RC2 version). I will add this to the documentation as soon as possible.

For more details about the `locked_sync` setting behavior, please check the [comments on the config file](https://github.com/gstt/laravel-achievements/blob/master/src/config/achievements.php)

**Comment by brjohnson4** [comment]
Oh, fantastic. Thanks! This worked perfectly.
